name: Docker push into docker hub

on: [push]

jobs:
  docker_hub:
    name: docker hub push to do project ji
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "hello Docker"
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Docker login
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175
        with:
          images: erdipu/node-todo-github
          
      - name: Build and Push to Docker hub
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
        
        
        
